name:  CD - Deploy Load Balancer

on:
  push:
    branches:
       - main

jobs:
  deploy:
    runs-on:  ubuntu-latest

    steps:
      - name:  Deploy to EC2 via SSH
        uses:  appleboy/ssh-action@v0.1.6
        with:
          host:  ${{ secrets.EC2_HOST }}
          username:  ${{ secrets.EC2_USER }}
          key:  ${{ secrets.EC2_SSH_KEY }}
          port:  22
          script:  |
            cd ~/projects/loadbalancer
            docker compose pull
            docker compose up -d
