name:  CD - Deploy Load Balancer

on:
  workflow_run:
    workflows:
      - CI Build and Push Image
    types:
      - completed

jobs:
  deploy:
    if:  ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on:  ubuntu-latest

    steps:
      - name:  Deploy to EC2 via SSH
        uses:  appleboy/ssh-action@v0.1.6
        with:
          host:  ${{ secrets.EC2_HOST }}
          username:  ${{ secrets.EC2_USER }}
          key:  ${{ secrets.EC2_SSH_KEY }}
          port:  22
          script:  |
            cd ~/projects/loadbalancer
            git pull
            export IMAGE_TAG=${{ github.event.workflow_run.head_sha }}
            docker compose pull
            docker compose up -d --remove-orphans --scale backend=3
