name:  CI Build and Push Image
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on:  ubuntu-latest
    steps:
      - name:  Checkout source code
        uses:  actions/checkout@v4

      - name:  Login to Docker Hub
        uses:  docker/login-action@v2

        with:
          username:  ${{ secrets.DOCKERHUB_USERNAME }}
          password:  ${{ secrets.DOCKERHUB_TOKEN }}

      - name:  Build Docker Image
        run:  |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/loadbalancer:latest ./back-end 

      - name:  Push Docker Image
        run:  |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/loadbalancer:latest
